# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
