# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20181029_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
