# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20181029_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
