# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20181105_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='client_ip',
            field=models.GenericIPAddressField(default='192.168.0.1'),
        ),
    ]
